-- Q1.
CREATE TABLE IF NOT EXISTS TEAM_INFO (
    TEAM_CODE INT AUTO_INCREMENT PRIMARY KEY COMMENT '소속코드',
    TEAM_NAME VARCHAR(100) NOT NULL COMMENT '소속명',
    TEAM_DETAIL VARCHAR(500) COMMENT '소속상세정보',
    USE_YN CHAR(2) NOT NULL COMMENT '사용여부',
    CHECK(USE_YN IN('Y','N'))
);

CREATE TABLE IF NOT EXISTS MEMBER_INFO (
    MEMBER_CODE INT AUTO_INCREMENT PRIMARY KEY COMMENT '회원코드',
    MEMBER_NAME VARCHAR(70) NOT NULL COMMENT '회원이름',
    BIRTHDATE DATE COMMENT '생년월일',
    DIVISION_CODE CHAR(2) COMMENT '구분코드',
    DETAIL_INFO VARCHAR(500) COMMENT '상세정보',
    CONTACT VARCHAR(50) NOT NULL COMMENT '연락처',
    TEAM_CODE INT NOT NULL COMMENT '소속코드',
    FOREIGN KEY(TEAM_CODE) REFERENCES TEAM_INFO(TEAM_CODE),
    ACTIVE_STATUS CHAR(2) DEFAULT 'Y' COMMENT '활동상태',
    CHECK(ACTIVE_STATUS IN('Y', 'N', 'H'))
);

-- Q2.
INSERT INTO TEAM_INFO (TEAM_NAME, TEAM_DETAIL, USE_YN)
VALUES ('음악감상부', '클래식 및 재즈 음악을 감상하는 사람들의 모임', 'Y');
INSERT INTO TEAM_INFO (TEAM_NAME, TEAM_DETAIL, USE_YN)
VALUES ('맛집탐방부', '맛집을 찾아다니는 사람들의 모임', 'N');
INSERT INTO TEAM_INFO (TEAM_NAME, TEAM_DETAIL, USE_YN)
VALUES ('행복찾기부', NULL, 'Y');

INSERT INTO MEMBER_INFO (MEMBER_NAME, BIRTHDATE, DIVISION_CODE, DETAIL_INFO, CONTACT, TEAM_CODE, ACTIVE_STATUS)
VALUES ('송가인', '1990-01-30', 1, '안녕하세요 송가인입니다~', '010-9494-9494', 1, 'H');
INSERT INTO MEMBER_INFO (MEMBER_NAME, BIRTHDATE, DIVISION_CODE, DETAIL_INFO, CONTACT, TEAM_CODE, ACTIVE_STATUS)
VALUES ('임영웅', '1992-05-03', NULL, '국민아들 임영웅입니다~', 'hero@trot.com', 1, 'Y');
INSERT INTO MEMBER_INFO (MEMBER_NAME, BIRTHDATE, DIVISION_CODE, DETAIL_INFO, CONTACT, TEAM_CODE, ACTIVE_STATUS)
VALUES ('태진아', NULL, NULL, NULL, '(1급기밀)', 3, 'Y');

-- 테이블 생성 확인
SELECT * FROM TEAM_INFO;
SELECT * FROM MEMBER_INFO;